name: data_scrapper
description: scrapper various things
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  args: ^2.3.1
  dio: ^4.0.4
  freezed_annotation: ^1.1.0
  gql_dio_link: ^0.2.2
  graphql: ^5.1.1
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.0
  json_serializable: ^6.1.4
  very_good_analysis: ^2.4.0
