name: build-and-upload-top-sales

env:
  DART_SDK_VERSION: 2.18.1

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    name: Build and upload Top Sales
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK_VERSION }}

      - name: Install NodeJS dependencies for firestore importer
        working-directory: ./firestore_importer
        run: npm install

      - name: Install Collection Builder dependencies
        run: dart pub get

      - name: Get firestore importer credentials
        working-directory: ./firestore_importer
        run: echo ${{ secrets.FIRESTORE_IMPORTER_CREDENTIALS }} | base64 --decode > credentials.json

      - name: Build Collections
        run: dart bin/main.dart

      - name: Upload Collections to Firebase
        working-directory: ./firestore_importer
        run: npm run migrate import ../top_sale_events.json
